// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// logL1
double logL1(const NumericMatrix coeffMatA, const NumericMatrix coeffMatB);
RcppExport SEXP _treenomial_logL1(SEXP coeffMatASEXP, SEXP coeffMatBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix >::type coeffMatA(coeffMatASEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type coeffMatB(coeffMatBSEXP);
    rcpp_result_gen = Rcpp::wrap(logL1(coeffMatA, coeffMatB));
    return rcpp_result_gen;
END_RCPP
}
// logL1Complex
double logL1Complex(const ComplexVector coeffMatA, const ComplexVector coeffMatB);
RcppExport SEXP _treenomial_logL1Complex(SEXP coeffMatASEXP, SEXP coeffMatBSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const ComplexVector >::type coeffMatA(coeffMatASEXP);
    Rcpp::traits::input_parameter< const ComplexVector >::type coeffMatB(coeffMatBSEXP);
    rcpp_result_gen = Rcpp::wrap(logL1Complex(coeffMatA, coeffMatB));
    return rcpp_result_gen;
END_RCPP
}
// wedgeFill
void wedgeFill(NumericMatrix baseMat, NumericMatrix shiftsMat, NumericMatrix resMat);
RcppExport SEXP _treenomial_wedgeFill(SEXP baseMatSEXP, SEXP shiftsMatSEXP, SEXP resMatSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type baseMat(baseMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type shiftsMat(shiftsMatSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type resMat(resMatSEXP);
    wedgeFill(baseMat, shiftsMat, resMat);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_treenomial_logL1", (DL_FUNC) &_treenomial_logL1, 2},
    {"_treenomial_logL1Complex", (DL_FUNC) &_treenomial_logL1Complex, 2},
    {"_treenomial_wedgeFill", (DL_FUNC) &_treenomial_wedgeFill, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_treenomial(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
