# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allBinaryTreeShapesReal <- function(numTips) {
    .Call('_treenomial_allBinaryTreeShapesReal', PACKAGE = 'treenomial', numTips)
}

allBinaryTreeShapesPhylo <- function(numTips) {
    .Call('_treenomial_allBinaryTreeShapesPhylo', PACKAGE = 'treenomial', numTips)
}

allBinaryTreeShapesComplex <- function(numTips) {
    .Call('_treenomial_allBinaryTreeShapesComplex', PACKAGE = 'treenomial', numTips)
}

wedgeExport <- function(A, B) {
    .Call('_treenomial_wedgeExport', PACKAGE = 'treenomial', A, B)
}

wedgeExportConv <- function(A, B) {
    .Call('_treenomial_wedgeExportConv', PACKAGE = 'treenomial', A, B)
}

alignCoeffs <- function(coeffs, type) {
    .Call('_treenomial_alignCoeffs', PACKAGE = 'treenomial', coeffs, type)
}

coeffMatListCpp <- function(wedgeOrders, type, tipLabA = " ", tipLabB = " ") {
    .Call('_treenomial_coeffMatListCpp', PACKAGE = 'treenomial', wedgeOrders, type, tipLabA, tipLabB)
}

compareCoeffRcpp <- function(coeffsList, method) {
    .Call('_treenomial_compareCoeffRcpp', PACKAGE = 'treenomial', coeffsList, method)
}

coeffDistRcpp <- function(coeffsList, method) {
    .Call('_treenomial_coeffDistRcpp', PACKAGE = 'treenomial', coeffsList, method)
}

juliaSet <- function(coeffs, pixelLength, center, maxZ) {
    .Call('_treenomial_juliaSet', PACKAGE = 'treenomial', coeffs, pixelLength, center, maxZ)
}

