# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

coeffDistRcpp <- function(coeffs, method, progressBar) {
    .Call('_treenomial_coeffDistRcpp', PACKAGE = 'treenomial', coeffs, method, progressBar)
}

wedgeFill <- function(baseMat, shiftsMat, resMat) {
    invisible(.Call('_treenomial_wedgeFill', PACKAGE = 'treenomial', baseMat, shiftsMat, resMat))
}

wedgeFillComplex <- function(baseMat, shiftsMat, resMat) {
    invisible(.Call('_treenomial_wedgeFillComplex', PACKAGE = 'treenomial', baseMat, shiftsMat, resMat))
}

